language: ruby
cache: bundler
addons:
  firefox: 60.0
services:
  - memcached
env:
  global:
    - HEADLESS=true
    - RAILS_DB_ADAPTER=mysql2
    - RAILS_TEST_DB_NAME=hitobito_test
rvm:
  - 2.5.5
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install sphinxsearch
  - echo '[mysqld]'              | sudo tee    /etc/mysql/conf.d/sort_buffer_size.cnf > /dev/null
  - echo 'sort_buffer_size = 2M' | sudo tee -a /etc/mysql/conf.d/sort_buffer_size.cnf > /dev/null
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE hitobito_test;'
install:
  - bundle install --path vendor/bundle
  - bundle exec rake webpacker:compile
script:
  - bundle exec rake db:create ci --trace
